# fly.toml app configuration file generated for realtaste on 2025-01-17T10:30:00Z

app = "realtaste"
primary_region = "sin"

[build]
  dockerfile = "backend/Dockerfile"

[experimental]
  auto_rollback = true

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1