# =============================================================================
# REALTASTE BACKEND - FLY.IO CONFIGURATION
# =============================================================================
# Production deployment configuration for RealTaste backend API
# This configuration deploys ONLY the backend service to Fly.io
#
# See https://fly.io/docs/reference/configuration/ for more information

app = 'realtaste'
primary_region = 'sin'  # Singapore region for optimal performance

[build]
  # Use the optimized backend-only Dockerfile
  dockerfile = 'backend/Dockerfile'
  # Build context is the root directory
  build_context = '.'

[env]
  # Production environment variables
  NODE_ENV = 'production'
  PORT = '3001'

[http_service]
  # Internal port that the app listens on
  internal_port = 3001
  # Force HTTPS for security
  force_https = true
  # Auto-scaling configuration
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Health check configuration
  [[http_service.checks]]
    grace_period = '10s'     # Time to wait before starting health checks
    interval = '30s'         # How often to run health checks
    restart_limit = 3        # Max restarts before marking as unhealthy
    timeout = '5s'           # Timeout for each health check
    path = '/health'         # Health check endpoint
    method = 'GET'
    
  # HTTP service options
  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

# Resource allocation
[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512