# fly.toml app configuration file generated for realtaste-api on 2025-05-23T21:32:23+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "realtaste"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'backend/Dockerfile'
  build_context = '..'

# [deploy]
#   release_command = "echo 'Deployment successful'"

[env]
  NODE_ENV = "production"
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "10s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
